张量的操作主要包括**张量的结构操作**和**张量的数学运算**。

张量结构操作诸如：**张量创建**，**索引切片**，**维度变换**，**合并分割**。

张量数学运算主要有：**标量运算**，**向量运算**，**矩阵运算**。另外我们会介绍张量运算的广播机制。

本篇我们介绍张量的结构操作。

### 一、创建张量

张量创建的许多方法和numpy中创建array的方法很像。

In [1]:
import tensorflow as tf
import numpy as np

创建常量

In [2]:
a = tf.constant([1,2,3], dtype = tf.float32)
tf.print(a)

[1 2 3]


In [3]:
b = tf.range(1,10,delta = 2)
tf.print(b)

[1 3 5 7 9]


In [11]:
# 最小0，间隔 2*3.14，100个数
c = tf.linspace(0.0, 2*3.14, 100)
tf.print(c)

[0 0.0634343475 0.126868695 ... 6.15313148 6.21656609 6.28]


In [12]:
d = tf.zeros([3,3])
tf.print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
a = tf.ones([3,3])
b = tf.zeros_like(a,dtype= tf.float32)
tf.print(a)
tf.print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
b = tf.fill([3,2], 15)
tf.print(b)

[[15 15]
 [15 15]
 [15 15]]


均匀随机分布

In [21]:
# 均匀分布随机
# 返回5*1的矩阵，产生于 minval 和 maxval 之间，产生的值是均匀分布的。
tf.random.set_seed(1.0)
a = tf.random.uniform([5], minval=0, maxval=10)
tf.print(a)

[1.65130854 9.01481247 6.30974197 4.34546089 2.9193902]


正态分布

tf.random_normal()函数用于从“服从指定正态分布的序列”中随机取出指定个数的值。

tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

- shape: 输出张量的形状，必选
- mean: 正态分布的均值，默认为0
- stddev: 正态分布的标准差，默认为1.0
- dtype: 输出的类型，默认为tf.float32
- seed: 随机数种子，是一个整数，当设置之后，每次生成的随机数都一样
- name: 操作的名称


In [22]:
# 正态分布随机
b = tf.random.normal([3,3], mean=0.0, stddev=1.0)
tf.print(b)

[[0.403087884 -1.0880208 -0.0630953535]
 [1.33655667 0.711760104 -0.489286453]
 [-0.764221311 -1.03724861 -1.25193381]]


tf.random.truncated_normal

shape 是张量维度，mean 是正态分布是均值，stddev是正态分布的标准差；

它是从截断的正态分布中输出随机值，虽然同样是输出正态分布，但是它生成的值是在距离均值两个标准差范围之内的，也就是说，在tf.truncated_normal中如果x的取值在区间（μ-2σ，μ+2σ）之外则重新进行选择。这样保证了生成的值都在均值附近。

In [24]:
#正态分布随机，剔除2倍方差以外数据重新生成
c = tf.random.truncated_normal((5,5), mean=0.0, stddev=1.0, dtype=tf.float32)
tf.print(c)

[[1.6940167 0.119693168 -1.15846 0.172604024 1.25393271]
 [-0.145777747 -0.167923927 0.242540851 -0.738488793 -0.0219556261]
 [0.847492576 0.101899959 0.628251433 0.510985792 0.676944315]
 [0.455615073 -0.928990066 0.778658688 0.383007079 -0.382015228]
 [1.66602075 0.938058078 -0.800548375 1.57435715 1.33503103]]


特殊矩阵

In [25]:
# 特殊矩阵
I = tf.eye(3,3) # 单位矩阵
tf.print(I)
tf.print(" ")

t = tf.linalg.diag([1,2,3]) # 对角阵
tf.print(t)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
 
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### 二、索引切片

张量的索引切片方式和 numpy 几乎是一样的。切片时支持缺省参数和省略号。

对于 tf.Variable, 可以通过索引和切片对部分元素进行修改。

对于提取张量的连续子区域，也可以使用 tf.slice.

此外，对于不规则的切片提取,可以使用
tf.gather,
tf.gather_nd,
tf.boolean_mask。

tf.boolean_mask 功能最为强大，它可以实现tf.gather,tf.gather_nd的功能，并且tf.boolean_mask 还可以实现布尔索引。

如果要通过修改张量的某些元素得到新的张量，可以使用tf.where，tf.scatter_nd。

In [26]:
tf.random.set_seed(3)
t = tf.random.uniform([5,5], minval=0, maxval=10, dtype=tf.int32)
tf.print(t)

[[4 7 4 2 9]
 [9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]
 [3 7 0 0 3]]


In [28]:
# 第0行
tf.print(t[0])

[4 7 4 2 9]


In [29]:
# 倒数第一行
tf.print(t[-1])

[3 7 0 0 3]


In [30]:
# 第1行第3列
tf.print(t[1, 3])
tf.print(t[1][3])

4
4


In [31]:
# 第1行至第3行
tf.print(t[1:4, :])
tf.print(tf.slice(t,[1,0],[3,5])) #tf.slice(input,begin_vector,size_vector)

[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]
[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]


In [32]:
# 第1行至最后一行，第0列到最后一列每隔两列取一列
tf.print(t[1:4, :4:2])

[[9 2]
 [7 7]
 [9 9]]


In [34]:
# 对变量来说，还可以使用索引和切片修改部分元素
x = tf.Variable([[1,2],[3,4]], dtype = tf.float32)
x[1,:].assign(tf.constant([0.0,0.0]))
tf.print(x)

[[1 2]
 [0 0]]


In [38]:
a = tf.random.uniform([3,3,3], minval=0, maxval=10, dtype=tf.int32)
tf.print(a)

[[[2 2 6]
  [5 7 6]
  [4 8 6]]

 [[4 6 3]
  [8 1 7]
  [3 1 3]]

 [[2 1 6]
  [3 1 8]
  [9 3 7]]]


In [39]:
# 省略号可以表示多个冒号
tf.print(a[..., 1])

[[2 7 8]
 [6 1 1]
 [1 1 3]]


以上切片方式相对规则，对于不规则的切片提取,可以使用tf.gather,tf.gather_nd,tf.boolean_mask。

考虑班级成绩册的例子，有4个班级，每个班级10个学生，每个学生7门科目成绩。可以用一个4×10×7的张量来表示。

In [42]:
scores = tf.random.uniform((4,10,7), minval=0, maxval=100 ,dtype=tf.int32)

tf.print(scores)


[[[39 28 49 ... 79 64 56]
  [59 84 79 ... 46 43 49]
  [29 70 1 ... 57 91 16]
  ...
  [81 54 99 ... 65 90 40]
  [12 56 22 ... 64 12 33]
  [92 78 34 ... 49 14 75]]

 [[95 78 97 ... 19 59 34]
  [88 26 22 ... 4 30 31]
  [52 28 8 ... 77 73 73]
  ...
  [51 30 26 ... 6 37 71]
  [8 92 78 ... 85 68 70]
  [39 51 15 ... 57 88 11]]

 [[52 34 75 ... 43 67 58]
  [89 73 3 ... 30 90 22]
  [58 13 24 ... 28 17 10]
  ...
  [77 32 72 ... 13 59 32]
  [26 9 4 ... 55 4 73]
  [3 57 50 ... 15 22 73]]

 [[53 26 37 ... 88 84 13]
  [95 32 69 ... 89 13 16]
  [28 56 16 ... 34 92 17]
  ...
  [57 38 24 ... 82 10 6]
  [9 91 36 ... 12 34 35]
  [62 46 65 ... 79 2 36]]]


In [43]:
# 抽取每个班级第0个学生，第5个学生，第9个学生的全部成绩
p = tf.gather(scores, [0,5,9], axis=1)
tf.print(p)

[[[39 28 49 ... 79 64 56]
  [80 30 77 ... 94 69 30]
  [92 78 34 ... 49 14 75]]

 [[95 78 97 ... 19 59 34]
  [73 58 62 ... 73 47 42]
  [39 51 15 ... 57 88 11]]

 [[52 34 75 ... 43 67 58]
  [86 96 33 ... 62 6 89]
  [3 57 50 ... 15 22 73]]

 [[53 26 37 ... 88 84 13]
  [12 39 35 ... 98 68 9]
  [62 46 65 ... 79 2 36]]]


In [45]:
# 抽取每个班级第0个学生，第5个学生，第9个学生的第1门课程，第3门课程，第6门课程成绩
q = tf.gather(tf.gather(scores,[0,5,9],axis=1), [1,3,6], axis=2)
tf.print(q)

[[[28 12 56]
  [30 84 30]
  [78 65 75]]

 [[78 20 34]
  [58 9 42]
  [51 13 11]]

 [[34 49 58]
  [96 57 89]
  [57 8 73]]

 [[26 74 13]
  [39 65 9]
  [46 54 36]]]


In [46]:
# 抽取第0个班级第0个学生，第2个班级的第4个学生，第3个班级的第6个学生的全部成绩
# indices的长度为采样样本的个数，每个元素为采样位置的坐标
s = tf.gather_nd(scores,indices = [(0,0),(2,4),(3,6)])
s

<tf.Tensor: id=221, shape=(3, 7), dtype=int32, numpy=
array([[39, 28, 49, 12, 79, 64, 56],
       [10, 65, 47,  7, 29, 13, 37],
       [34, 64, 10, 34, 50, 64, 34]], dtype=int32)>

以上tf.gather和tf.gather_nd的功能也可以用tf.boolean_mask来实现。



In [47]:
# 抽取每个班级第0个学生，第5个学生，第9个学生的全部成绩
p = tf.boolean_mask(scores,[True,False,False,False,False,
                            True,False,False,False,True], axis=1)
tf.print(p)


[[[39 28 49 ... 79 64 56]
  [80 30 77 ... 94 69 30]
  [92 78 34 ... 49 14 75]]

 [[95 78 97 ... 19 59 34]
  [73 58 62 ... 73 47 42]
  [39 51 15 ... 57 88 11]]

 [[52 34 75 ... 43 67 58]
  [86 96 33 ... 62 6 89]
  [3 57 50 ... 15 22 73]]

 [[53 26 37 ... 88 84 13]
  [12 39 35 ... 98 68 9]
  [62 46 65 ... 79 2 36]]]


In [48]:
# 抽取第0个班级第0个学生，第2个班级的第4个学生，第3个班级的第6个学生的全部成绩
s = tf.boolean_mask(scores,
    [[True,False,False,False,False,False,False,False,False,False],
     [False,False,False,False,False,False,False,False,False,False],
     [False,False,False,False,True,False,False,False,False,False],
     [False,False,False,False,False,False,True,False,False,False]])
tf.print(s)

[[39 28 49 ... 79 64 56]
 [10 65 47 ... 29 13 37]
 [34 64 10 ... 50 64 34]]


In [49]:
#利用tf.boolean_mask可以实现布尔索引

#找到矩阵中小于0的元素
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)
tf.print(c,"\n")

tf.print(tf.boolean_mask(c,c<0),"\n") 
tf.print(c[c<0]) # 布尔索引，为boolean_mask的语法糖形式

[[-1 1 -1]
 [2 2 -2]
 [3 -3 3]] 

[-1 -1 -2 -3] 

[-1 -1 -2 -3]


以上这些方法仅能提取张量的部分元素值，但不能更改张量的部分元素值得到新的张量。

如果要通过修改张量的部分元素值得到新的张量，可以使用tf.where和tf.scatter_nd。

tf.where可以理解为if的张量版本，此外它还可以用于找到满足条件的所有元素的位置坐标。

tf.scatter_nd的作用和tf.gather_nd有些相反，tf.gather_nd用于收集张量的给定位置的元素，

而tf.scatter_nd可以将某些值插入到一个给定shape的全0的张量的指定位置处。

In [52]:
#找到张量中小于0的元素,将其换成np.nan得到新的张量
#tf.where和np.where作用类似，可以理解为if的张量版本

c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)
d = tf.where(c<0, tf.fill(c.shape,np.nan), c) 
d

<tf.Tensor: id=358, shape=(3, 3), dtype=float32, numpy=
array([[nan,  1., nan],
       [ 2.,  2., nan],
       [ 3., nan,  3.]], dtype=float32)>

In [51]:
#如果where只有一个参数，将返回所有满足条件的位置坐标
indices = tf.where(c<0)
indices

<tf.Tensor: id=351, shape=(4, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [1, 2],
       [2, 1]])>

In [53]:
# 将张量的第[0,0]和[2,1]两个位置元素替换为0得到新的张量
d = c - tf.scatter_nd([[0,0],[2,1]],[c[0,0],c[2,1]],c.shape)
d

<tf.Tensor: id=371, shape=(3, 3), dtype=float32, numpy=
array([[ 0.,  1., -1.],
       [ 2.,  2., -2.],
       [ 3.,  0.,  3.]], dtype=float32)>

In [54]:
#scatter_nd的作用和gather_nd有些相反
#可以将某些值插入到一个给定shape的全0的张量的指定位置处。
indices = tf.where(c<0)
tf.scatter_nd(indices,tf.gather_nd(c,indices),c.shape)

<tf.Tensor: id=377, shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0., -1.],
       [ 0.,  0., -2.],
       [ 0., -3.,  0.]], dtype=float32)>

### 三、维度变换

维度变换相关函数主要有 tf.reshape, tf.squeeze, tf.expand_dims, tf.transpose.

tf.reshape 可以改变张量的形状。

tf.squeeze 可以减少维度。

tf.expand_dims 可以增加维度。

tf.transpose 可以交换维度。

tf.reshape可以改变张量的形状，但是其本质上不会改变张量元素的存储顺序，所以，该操作实际上非常迅速，并且是可逆的。

In [55]:
a = tf.random.uniform(shape=[1,3,3,2],
                      minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)
tf.print(a)

TensorShape([1, 3, 3, 2])
[[[[158 90]
   [89 14]
   [59 209]]

  [[91 164]
   [239 138]
   [156 95]]

  [[48 40]
   [0 238]
   [3 22]]]]


In [56]:
# 改成 （3,6）形状的张量
b = tf.reshape(a,[3,6])
tf.print(b.shape)
tf.print(b)

TensorShape([3, 6])
[[158 90 89 14 59 209]
 [91 164 239 138 156 95]
 [48 40 0 238 3 22]]


In [57]:
# 改回成 [1,3,3,2] 形状的张量
c = tf.reshape(b,[1,3,3,2])
tf.print(c)

[[[[158 90]
   [89 14]
   [59 209]]

  [[91 164]
   [239 138]
   [156 95]]

  [[48 40]
   [0 238]
   [3 22]]]]


如果张量在某个维度上只有一个元素，利用tf.squeeze可以消除这个维度。

和tf.reshape相似，它本质上不会改变张量元素的存储顺序。

张量的各个元素在内存中是线性存储的，其一般规律是，同一层级中的相邻元素的物理地址也相邻。

In [58]:
s = tf.squeeze(a)
tf.print(s.shape)
tf.print(s)

TensorShape([3, 3, 2])
[[[158 90]
  [89 14]
  [59 209]]

 [[91 164]
  [239 138]
  [156 95]]

 [[48 40]
  [0 238]
  [3 22]]]


In [59]:
d = tf.expand_dims(s,axis=0) #在第0维插入长度为1的一个维度
d

<tf.Tensor: id=395, shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[158,  90],
         [ 89,  14],
         [ 59, 209]],

        [[ 91, 164],
         [239, 138],
         [156,  95]],

        [[ 48,  40],
         [  0, 238],
         [  3,  22]]]], dtype=int32)>